### ISSUE TITLE
Consistent synopsis for "install all" and "install components" scripts

### ISSUE THREAD

**Issue by skalee** [riboseinc/gpg-build-scripts#14]
The `install_gpg_all.sh` script requires passing suite version with `-i` argument.
The `install_gpg_component.sh` script requires passing component version with `--version` argument.

1. This inconsistency should be resolved.
2. `--version` is a bad name for argument, because `<program> --version` conventionally prints out program version. Perhaps `--at-version` or `--at`?

@ronaldtse, any idea what `-i` could mean? It has been introduced in your commit.

**Comment by ronaldtse** [comment]
Sorry, I don’t actually remember. I wonder if it stood for “install” :cry:

—at is definitely better than —version.

**Comment by skalee** [comment]
I believe this one can be considered fixed as of #17.

**Comment by ronaldtse** [comment]
Thanks @skalee !
