### ISSUE TITLE
Create README and build badges

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gpg-build-scripts#2]
As title.

**Comment by skalee** [comment]
@ronaldtse Please enable Travis for this repo. Apart from that, please change the main branch from "install-scripts" to "master" in repo settings.

**Comment by ronaldtse** [comment]
@skalee Travis was always on, but seems that Travis can only see the `install-scripts` branch right now. I've updated the main branch to master, let's see if Travis gets triggered for new commits. Thanks.

**Comment by ronaldtse** [comment]
P.S We still need a README, thanks.
