### ISSUE TITLE
`all` script not working in CentOS 7 container

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gpg-build-scripts#4]
The `component` script requires a mandatory option `--build-dir` which is not provided by the `all` script. There probably should be a default build directory in the `component` script or the `all`.

**Comment by skalee** [comment]
I can create a tempdir, if none provided.

**Comment by ronaldtse** [comment]
Sure; but the “all” script should provide some sort of help and if any arguments are necessary, it should throw an error.

**Comment by skalee** [comment]
It actually does. An error from "component" script occurs. I just wrote README, it may clarify few things.

**Comment by ronaldtse** [comment]
Thanks. Also fixed in #6.

**Comment by skalee** [comment]
Actually I'm preparing a CentOS Docker file at the moment, but given #6 I have doubts if it is necessary.

**Comment by ronaldtse** [comment]
Cool, then since it works, let's close this for now, we can cleanup the scripts later.
